name: lti

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ats_user
      POSTGRES_PASSWORD: ats_password
      POSTGRES_DB: ats_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
